In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\HP\Documents\day12-cleaned.csv")

In [3]:
df.shape

(9994, 9)

In [4]:
df.head()

,Order ID,Product ID,Customer ID,Order Date,Postal Code,Sales,Profit,Discount,Quantity
0,CA-2016-152156,FUR-CH-10000454,CG-12520,11-Aug-16,42420,? 731.94,? 219.582,0.0,3
1,CA-2015-106320,FUR-TA-10000577,EB-13870,25-Sep-15,84057,"? 1,044.63",? 240.2649,0.0,3
2,CA-2016-121755,TEC-AC-10003027,EH-13945,16-Jan-16,90049,? 90.57,? 11.7741,0.0,3
3,CA-2016-169194,TEC-AC-10002167,LH-16900,20-Jun-16,19901,? 45.,? 4.95,0.0,3
4,CA-2015-135545,OFF-PA-10003892,KM-16720,24-Nov-15,90004,? 146.73,? 68.9631,0.0,3

In [5]:
df.tail()

,Order ID,Product ID,Customer ID,Order Date,Postal Code,Sales,Profit,Discount,Quantity
9989,CA-2016-105781,FUR-CH-10001802,JF-15565,16-Feb-16,10024,? 326.646,? 39.9234,0.10,3
9990,CA-2017-144491,FUR-BO-10001811,CJ-12010,27-Mar-17,77070,"? 1,023.332",30.098 -?,0.32,5
9991,CA-2016-122581,FUR-CH-10002961,JK-15370,21-Aug-16,10035,? 573.174,? 63.686,0.10,7
9992,CA-2015-104948,FUR-BO-10004357,KH-16510,13-Nov-15,92404,? 683.332,40.196 -?,0.15,4
9993,CA-2015-168088,FUR-BO-10004218,CM-12655,19-Mar-15,77041,? 383.4656,67.6704 -?,0.32,4

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9994 non-null   object
 1   Product ID   9994 non-null   object
 2   Customer ID  9994 non-null   object
 3   Order Date   9994 non-null   object
 4   Postal Code  9994 non-null   int64
 5   Sales        9994 non-null   object
 6   Profit       9994 non-null   object
 7   Discount     9994 non-null   float64
 8   Quantity     9994 non-null   int64
dtypes: float64(1), int64(2), object(6)
memory usage: 702.8+ KB

In [7]:
df.describe()

        Postal Code     Discount     Quantity
count   9994.000000  9994.000000  9994.000000
mean   55190.379428     0.156203     3.789574
std    32063.693350     0.206452     2.225110
min     1040.000000     0.000000     1.000000
25%    23223.000000     0.000000     2.000000
50%    56430.500000     0.200000     3.000000
75%    90008.000000     0.200000     5.000000
max    99301.000000     0.800000    14.000000

In [9]:
df.shape[0]

9994

In [10]:
df.shape[1]

9

In [11]:
df.isnull().sum()

Order ID       0
Product ID     0
Customer ID    0
Order Date     0
Postal Code    0
Sales          0
Profit         0
Discount       0
Quantity       0
dtype: int64